apiVersion: v1
kind: ReplicationController
metadata:
  name: node-workflow
  label: node-workflow
spec:
  replicas: 1
  selector:
    name: node-workflow
  template:
    meta:
      label: node-workflow
    spec:
      containers:
        - name: node-docker-workflow
          image: zerosoftwere/node-docker-workflow
          ports:
            - containerPort: 80
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
